persistence:
  postgresql:
    secretRef:
      name: backstage-psql-secret-developer-hub
      userKey: POSTGRES_USER
      passwordKey: POSTGRES_PASSWORD
    serviceRef:
      name: backstage-psql-developer-hub
      port: 5432
      databaseName: backstage_plugin_orchestrator
      databaseSchema: create-ocp-namespace-swt

image: 
  repository: quay.io/evanshortiss/swf-create-ocp-namespace-swt
  tag: latest

backstage:
  softwareTemplateNamespace:

secret:
  backstageToken: orchestrator-backstage-backend-token
  gitlabToken: orchestrator-gitlab-token